/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Pattern approach for better coverage
    {
      pattern: /^(bg-gradient-to-|from-|via-|to-)(r|l|t|b|tr|tl|br|bl|amber|yellow|orange|green|emerald|blue|purple|indigo|gray|black|white)(-\d+)?(\/(10|20|30|40|50|60|70|80|90|95))?$/,
    },
    {
      pattern: /^(hover:|group-hover:|focus:)?(bg-|text-|border-|ring-)(amber|yellow|orange|green|emerald|blue|purple|indigo|gray|black|white)(-\d+)?(\/(10|20|30|40|50|60|70|80|90|95))?$/,
    },
    {
      pattern: /^(scale-|translate-|rotate-|skew-)\d+$/,
    },
    {
      pattern: /^(hover:|group-hover:)?(scale-|translate-|rotate-|skew-)\d+$/,
    },
    // Specific classes that need to be always included
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'bg-gradient-to-t',
    'bg-gradient-to-tr',
    'via-transparent',
    'via-black/50',
    'from-black/70',
    'from-black/80',
    'to-black/30',
    'to-transparent',
    'backdrop-blur-sm',
    'backdrop-blur-xl',
    'animate-pulse',
    'animate-spin',
    'animate-in',
    'fade-in',
    'duration-300',
    'duration-500',
    'duration-700',
    'transition-all',
    'transition-transform',
    'transition-colors',
    'transition-opacity',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    'hover:shadow-lg',
    'hover:shadow-xl',
    'hover:shadow-2xl',
    'ring-4',
    'ring-offset-2',
    'opacity-0',
    'opacity-50',
    'opacity-80',
    'opacity-100',
    'hover:opacity-100',
    'group-hover:opacity-100',
    'hover:-translate-y-1',
    'hover:scale-100',
    'hover:scale-105',
    'hover:scale-110',
    'group-hover:scale-105',
    'group-hover:scale-110',
    
    // Green classes for Eco Bắc Giang
    'from-green-400',
    'to-emerald-600',
    'from-green-500',
    'to-emerald-600',
    'from-green-600',
    'to-emerald-700',
    'from-green-600',
    'to-blue-600',
    'from-blue-600',
    'to-green-600',
    'from-green-700',
    'to-emerald-800',
    'hover:from-green-700',
    'hover:to-emerald-800',
    'bg-green-100',
    'bg-green-50',
    'text-green-600',
    'text-green-700',
    'border-green-200',
    
    // Amber classes for PropertyDetail
    'from-amber-400',
    'to-amber-600',
    'from-amber-500', 
    'to-amber-600',
    'from-amber-600',
    'to-amber-700',
    'hover:from-amber-600',
    'hover:to-amber-700',
    'bg-amber-400',
    'bg-amber-500',
    'text-amber-100',
    'text-amber-300',
    'text-amber-400',
    'text-amber-600',
    'border-amber-200',
    'border-amber-300',
    'border-amber-400',
    'hover:border-amber-200',
    'focus:border-amber-400',
    'ring-amber-400',
    'bg-amber-400/10',
    'bg-amber-300/10',
    
    // Purple, Blue, Emerald
    'from-purple-400',
    'to-purple-600',
    'from-blue-400',
    'to-blue-600',
    'from-blue-500',
    'to-blue-600', 
    'from-emerald-400',
    'to-emerald-600',
    'bg-purple-100',
    'bg-blue-100', 
    'bg-emerald-100',
    'bg-emerald-50',
    'text-purple-600',
    'text-blue-600',
    'text-emerald-600',
    'text-emerald-700',
    'border-purple-100',
    'border-purple-200',
    'border-blue-100',
    'border-blue-200',
    'border-emerald-100',
    'border-emerald-200',
    'hover:border-purple-200',
    'hover:border-blue-200',
    'hover:border-emerald-200',
    
    // Additional gradient classes for hero section
    'from-purple-100',
    'via-blue-50',
    'to-indigo-100',
    'from-purple-500',
    'to-pink-500',
    'from-green-500',
    'to-blue-500',
    'from-pink-500',
    'to-red-500',
    'from-blue-500',
    'to-purple-500',
    'from-blue-500',
    'to-teal-500',
    'via-blue-500',
    'to-indigo-600',
    'bg-purple-50',
    'bg-indigo-100',
    'bg-indigo-50'
  ],
  theme: {
    extend: {
      animation: {
        blink: "blink 1.5s infinite",
      },
      keyframes: {
        blink: {
          "0%, 100%": { backgroundColor: "rgb(34, 197, 94)" }, // màu xanh
          "50%": { backgroundColor: "#f97316" }, // màu đỏ
        },
      },
      fontFamily: {
        heading: ["var(--ltn__heading-font)", "sans-serif"], // Sử dụng font Rajdhani
      },
      colors: {
        "primary-dark": "#1f1f1f",
        primary: "#ffffff",
        highlight: {
          dark: "#FFFFFF",
          light: "#1f1f1f",
        },
        secondary: {
          dark: "#707070",
          light: "#e6e6e6",
        },
        action: "#059669", // Emerald-600
        brand: {
          50: "#ecfdf5",
          100: "#d1fae5", 
          200: "#a7f3d0",
          300: "#6ee7b7",
          400: "#34d399",
          500: "#10b981",
          600: "#059669",
          700: "#047857",
          800: "#065f46",
          900: "#064e3b",
        },
      },
      transitionProperty: {
        width: "width",
      },
    },
    extend: {
      backgroundImage: {
        "png-pattern": "url('/empty-bg.jpg')",
        "gradient-to-b": "linear-gradient(to bottom, #10b981, #059669)",
        "gradient-brand": "linear-gradient(135deg, #10b981 0%, #059669 50%, #047857 100%)",
        "gradient-brand-light": "linear-gradient(135deg, #ecfdf5 0%, #d1fae5 50%, #a7f3d0 100%)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("tailwind-scrollbar")],
};
